// src/mystery_box/pools.ts
// The data layer: 13 trait pools keyed by category.
//
// Starter pools: ~6 entries per category, spread across the 5 bands.
// Spec target is 30–60 per category — grow these in a follow-up commit.
// Adding entries does NOT require touching any logic.

import type { TraitPool } from "../types.js";

const NAMES: TraitPool = [
  // Common (21) — ordinary first names from any real office, deadpan realism
  { value: "Steve",   band: "Common" },
  { value: "Karen",   band: "Common" },
  { value: "Dave",    band: "Common" },
  { value: "Linda",   band: "Common" },
  { value: "Keith",   band: "Common" },
  { value: "Susan",   band: "Common" },
  { value: "Colin",   band: "Common" },
  { value: "Barbara", band: "Common" },
  { value: "Gary",    band: "Common" },
  { value: "Janet",   band: "Common" },
  { value: "Trevor",  band: "Common" },
  { value: "Pauline", band: "Common" },
  { value: "Nigel",   band: "Common" },
  { value: "Margaret", band: "Common" },
  { value: "Ian",     band: "Common" },
  { value: "Sheila",  band: "Common" },
  { value: "Doreen",  band: "Common" },
  { value: "Carol",   band: "Common" },
  { value: "Priya",   band: "Common" },
  { value: "Yusuf",   band: "Common" },
  { value: "Aoife",   band: "Common" },

  // Uncommon (12) — distinctive names, mix of British-uncommon and international
  { value: "Derek",   band: "Uncommon" },
  { value: "Bernard", band: "Uncommon" },
  { value: "Agatha",  band: "Uncommon" },
  { value: "Humphrey", band: "Uncommon" },
  { value: "Hans",    band: "Uncommon" },
  { value: "Siobhan", band: "Uncommon" },
  { value: "Kenji",   band: "Uncommon" },
  { value: "Ingrid",  band: "Uncommon" },
  { value: "Rajesh",  band: "Uncommon" },
  { value: "Małgorzata", band: "Uncommon" },
  { value: "Tomasz",  band: "Uncommon" },
  { value: "Niamh",   band: "Uncommon" },

  // Rare (7) — first name + office-shorthand qualifier
  { value: "Brenda from Accounts", band: "Rare" },
  { value: "Dave who used to be a contractor", band: "Rare" },
  { value: "Linda on the third floor", band: "Rare" },
  { value: "the other Steve", band: "Rare" },
  { value: "Nick from Procurement (not that Nick)", band: "Rare" },
  { value: "Tall Paul", band: "Rare" },
  { value: "Susan from the London office", band: "Rare" },

  // Legendary (3) — memorable one-word or titled names
  { value: "Günther", band: "Legendary" },
  { value: "Mx. Featherington", band: "Legendary" },
  { value: "Ambrose", band: "Legendary" },

  // Mythic (2) — names that are statements about the person
  { value: "The One Who Doesn't Speak", band: "Mythic" },
  { value: "She Who Approves Expense Reports", band: "Mythic" },
];

const JOB_TITLES: TraitPool = [
  // Common (21) — realistic job titles you'd see on a real org chart
  { value: "Senior Developer",          band: "Common" },
  { value: "QA Lead",                   band: "Common" },
  { value: "Account Executive",         band: "Common" },
  { value: "IT Support Technician",     band: "Common" },
  { value: "Office Manager",            band: "Common" },
  { value: "Junior Analyst",            band: "Common" },
  { value: "Operations Coordinator",    band: "Common" },
  { value: "Project Manager",           band: "Common" },
  { value: "Marketing Associate",       band: "Common" },
  { value: "Business Analyst",          band: "Common" },
  { value: "HR Generalist",             band: "Common" },
  { value: "Finance Manager",           band: "Common" },
  { value: "Executive Assistant",       band: "Common" },
  { value: "Sales Representative",      band: "Common" },
  { value: "Product Designer",          band: "Common" },
  { value: "Data Engineer",             band: "Common" },
  { value: "Customer Success Manager",  band: "Common" },
  { value: "Technical Writer",          band: "Common" },
  { value: "Procurement Officer",       band: "Common" },
  { value: "Facilities Coordinator",    band: "Common" },
  { value: "Payroll Administrator",     band: "Common" },

  // Uncommon (12) — real but slightly baroque corporate titles
  { value: "Regional Manager",          band: "Uncommon" },
  { value: "Senior Customer Success Enablement Specialist", band: "Uncommon" },
  { value: "Head of Stakeholder Relations", band: "Uncommon" },
  { value: "Principal Product Evangelist", band: "Uncommon" },
  { value: "Director of Strategic Initiatives", band: "Uncommon" },
  { value: "VP of People Operations",   band: "Uncommon" },
  { value: "Chief of Staff to the COO", band: "Uncommon" },
  { value: "Lead Synergy Architect",    band: "Uncommon" },
  { value: "Global Head of Learning and Development", band: "Uncommon" },
  { value: "Senior Manager, Digital Transformation", band: "Uncommon" },
  { value: "Associate Director of Thought Leadership", band: "Uncommon" },
  { value: "Head of Paid Search",       band: "Uncommon" },

  // Rare (7) — dry-funny titles that could plausibly exist in a dysfunctional office
  { value: "ASCII Comptroller",         band: "Rare" },
  { value: "Head of Mug Allocation",    band: "Rare" },
  { value: "Chair of the Fridge Cleaning Rota", band: "Rare" },
  { value: "Warden of the Second-Floor Printer", band: "Rare" },
  { value: "Chair of the Meeting Room Booking Committee", band: "Rare" },
  { value: "Deputy Director of Badge Reissue", band: "Rare" },
  { value: "Vice-Chair of the Birthday Card Subcommittee", band: "Rare" },

  // Legendary (3) — invented Michael-Scott-style titles
  { value: "Wizard of Light Bulb Moments", band: "Legendary" },
  { value: "Chancellor of Nearly-Caught-Up Emails", band: "Legendary" },
  { value: "Grand Architect of the Shared Drive", band: "Legendary" },

  // Mythic (2) — cosmic corporate titles with religious/mythic scale
  { value: "Galactic Viceroy of Research Excellence", band: "Mythic" },
  { value: "Eternal Custodian of the Quarterly Roadmap", band: "Mythic" },
];

const DESK_SETUPS: TraitPool = [
  // Common (21) — boring, recognisable office detritus
  { value: "a single dying succulent",                                            band: "Common" },
  { value: "a coffee mug labelled WORLD'S OKAYEST DBA",                           band: "Common" },
  { value: "a half-drunk mug of cold tea",                                        band: "Common" },
  { value: "a tower of Post-its nobody has read",                                 band: "Common" },
  { value: "an ergonomic keyboard they never use",                                band: "Common" },
  { value: "a framed photo of a dog that isn't theirs",                           band: "Common" },
  { value: "a wrist rest flattened by years of use",                              band: "Common" },
  { value: "a desk fan angled at exactly one shoulder",                           band: "Common" },
  { value: "a tangle of three different charging cables",                         band: "Common" },
  { value: "a bowl of mints from a 2019 conference",                              band: "Common" },
  { value: "a stress ball with the logo worn off",                                band: "Common" },
  { value: "a cracked mousepad held together with tape",                          band: "Common" },
  { value: "a stack of unopened internal newsletters",                            band: "Common" },
  { value: "a wobbly monitor riser made of old textbooks",                        band: "Common" },
  { value: "a water bottle with a faded motivational slogan",                     band: "Common" },
  { value: "a pen pot containing only dead biros",                                band: "Common" },
  { value: "a laminated fire evacuation map from two offices ago",                band: "Common" },
  { value: "a wall calendar still showing last February",                         band: "Common" },
  { value: "a drawer that only opens halfway",                                    band: "Common" },
  { value: "an office chair missing one armrest",                                 band: "Common" },
  { value: "a half-eaten cereal bar from Tuesday",                                band: "Common" },
  // Uncommon (12) — mildly personal, slightly revealing
  { value: "a moleskine that nobody has ever seen open",                          band: "Uncommon" },
  { value: "a tiny zen garden raked into tight spirals",                          band: "Uncommon" },
  { value: "a printed spreadsheet annotated in three colours of highlighter",     band: "Uncommon" },
  { value: "a photo of themselves shaking hands with a minor politician",         band: "Uncommon" },
  { value: "a Rubik's cube solved on exactly one face",                           band: "Uncommon" },
  { value: "a terrarium of moss they whisper to",                                 band: "Uncommon" },
  { value: "a handwritten list of enemies, folded twice",                         band: "Uncommon" },
  { value: "a small trophy for a fun run they didn't finish",                     band: "Uncommon" },
  { value: "a jar of elastic bands sorted by thickness",                          band: "Uncommon" },
  { value: "a chipped teacup inherited from a grandmother",                       band: "Uncommon" },
  { value: "a noise-cancelling headset worn even during lunch",                   band: "Uncommon" },
  { value: "a postcard from nowhere in particular, pinned up for nine years",     band: "Uncommon" },
  // Rare (7) — excessive, pointed, conspicuous
  { value: "a 9-monitor day-trading rig",                                         band: "Rare" },
  { value: "a standing desk stuck permanently at its highest setting",            band: "Rare" },
  { value: "a full mechanical keyboard wired to a foot pedal",                    band: "Rare" },
  { value: "an aquarium of increasingly anxious goldfish",                        band: "Rare" },
  { value: "a collection of seventeen identical black notebooks",                 band: "Rare" },
  { value: "a framed cease-and-desist letter displayed with pride",               band: "Rare" },
  { value: "a desk entirely carpeted in press clippings about themselves",        band: "Rare" },
  // Legendary (3) — folklore, whispered-about
  { value: "forty unwashed mugs in a stable equilibrium",                         band: "Legendary" },
  { value: "a potted fern that has outlived three managers and a merger",         band: "Legendary" },
  { value: "a chair that creaks in a rhythm nobody can quite place",              band: "Legendary" },
  // Mythic (2) — surreal, impossible
  { value: "a full-size cardboard cutout of Nicolas Cage",                        band: "Mythic" },
  { value: "a second identical desk facing theirs, always occupied, never explained", band: "Mythic" },
];

const HABITS: TraitPool = [
  // Common (21) — mundane office annoyances
  { value: "sends emails at midnight",                                       band: "Common" },
  { value: "replies-all to everything",                                      band: "Common" },
  { value: "reads every email aloud before sending",                         band: "Common" },
  { value: "eats crisps at their desk throughout every meeting",             band: "Common" },
  { value: "prints every document 'just in case'",                           band: "Common" },
  { value: "chews ice loudly at the standing desk",                          band: "Common" },
  { value: "leaves voicemails instead of sending a message",                 band: "Common" },
  { value: "clears their throat before every sentence",                      band: "Common" },
  { value: "schedules meetings to discuss upcoming meetings",                band: "Common" },
  { value: "takes the stairs and mentions it each time",                     band: "Common" },
  { value: "forgets their password every Monday morning",                    band: "Common" },
  { value: "brings a banana to every meeting and never eats it",             band: "Common" },
  { value: "refuses to use the shared calendar",                             band: "Common" },
  { value: "sighs audibly before answering any question",                    band: "Common" },
  { value: "arrives exactly nine minutes early, every single day",           band: "Common" },
  { value: "keeps a jumper on the back of their chair year-round",           band: "Common" },
  { value: "asks if a meeting 'could have been an email' during the meeting", band: "Common" },
  { value: "types with two fingers and surprising speed",                    band: "Common" },
  { value: "rearranges the dishwasher after everyone else has loaded it",    band: "Common" },
  { value: "reuses the same tea bag across three separate mugs",             band: "Common" },
  { value: "refers to the CEO by their first name in every sentence",        band: "Common" },

  // Uncommon (12) — mildly unprofessional
  { value: "microwaves fish despite three separate HR warnings",             band: "Uncommon" },
  { value: "takes loud personal calls in the open-plan office",              band: "Uncommon" },
  { value: "forwards motivational quotes to the whole team on Mondays",      band: "Uncommon" },
  { value: "never wears the ID badge and argues with reception daily",       band: "Uncommon" },
  { value: "leaves passive-aggressive sticky notes on the communal fridge",  band: "Uncommon" },
  { value: "books the largest meeting room for solo calls",                  band: "Uncommon" },
  { value: "clips their fingernails at the desk on Wednesday afternoons",    band: "Uncommon" },
  { value: "keeps the out-of-office autoresponder on while sitting at the desk", band: "Uncommon" },
  { value: "corrects other people's grammar in the team chat",               band: "Uncommon" },
  { value: "brings a full home-cooked curry to eat at the hot desk",         band: "Uncommon" },
  { value: "hot-desks in a different chair every day to avoid being found",  band: "Uncommon" },
  { value: "replies to Slack threads from six weeks ago with no context",    band: "Uncommon" },

  // Rare (7) — fully unprofessional
  { value: "hums Enya during code reviews",                                  band: "Rare" },
  { value: "keeps a whiteboard nobody else is allowed to clean",             band: "Rare" },
  { value: "names each office plant and cc's them in client emails",         band: "Rare" },
  { value: "conducts one-on-ones exclusively while walking backwards",       band: "Rare" },
  { value: "ends every message with a Latin phrase they cannot translate",   band: "Rare" },
  { value: "brings a portable ring light to in-person meetings",             band: "Rare" },
  { value: "keeps a locked filing cabinet no one has seen the key to",       band: "Rare" },

  // Legendary (3) — office folklore territory
  { value: "kept a folding cot in a server cabinet during a year-long migration", band: "Legendary" },
  { value: "once mediated a two-year feud between Finance and Procurement with a single PowerPoint slide", band: "Legendary" },
  { value: "has been quoted in three separate all-hands meetings without ever being present", band: "Legendary" },

  // Mythic (2) — paranormal
  { value: "has not spoken in a meeting since 2019 and still gets bonuses",  band: "Mythic" },
  { value: "appears in every team photo going back to 2004, including ones taken before they were hired", band: "Mythic" },
];

const COFFEE_RITUALS: TraitPool = [
  { value: "black coffee, no nonsense",                                    band: "Common" },
  { value: "tea with milk, exactly one sugar",                             band: "Common" },
  { value: "filter coffee with two sugars",                                band: "Common" },
  { value: "Yorkshire Tea, strong",                                        band: "Common" },
  { value: "tap water, room temperature",                                  band: "Common" },
  { value: "instant coffee from the kitchen jar",                          band: "Common" },
  { value: "a flat white from the place downstairs",                       band: "Common" },
  { value: "Earl Grey, no milk",                                           band: "Common" },
  { value: "a can of Diet Coke at 9 a.m.",                                 band: "Common" },
  { value: "green tea, steeped too long",                                  band: "Common" },
  { value: "a builder's brew in a chipped mug",                            band: "Common" },
  { value: "hot water with a slice of lemon",                              band: "Common" },
  { value: "a cappuccino, extra foam",                                     band: "Common" },
  { value: "a latte with oat milk",                                        band: "Common" },
  { value: "decaf, but they don't advertise it",                           band: "Common" },
  { value: "peppermint tea in the afternoon",                              band: "Common" },
  { value: "a smoothie from the chain on the corner",                      band: "Common" },
  { value: "a can of Red Bull before every stand-up",                      band: "Common" },
  { value: "chamomile tea after lunch",                                    band: "Common" },
  { value: "sparkling water, no ice",                                      band: "Common" },
  { value: "a bottle of Lucozade they refill at the tap",                  band: "Common" },
  { value: "a protein shake that smells like vanilla",                     band: "Uncommon" },
  { value: "a French press brewed at the desk every morning",              band: "Uncommon" },
  { value: "a V60 pour-over with a timer and a scale",                     band: "Uncommon" },
  { value: "yerba mate from a gourd with a metal straw",                   band: "Uncommon" },
  { value: "a matcha latte whisked by hand at their desk",                 band: "Uncommon" },
  { value: "cold brew they steeped themselves, 18 hours",                  band: "Uncommon" },
  { value: "a thermos of bone broth they sip through meetings",            band: "Uncommon" },
  { value: "an AeroPress with three custom tweaks nobody asked about",     band: "Uncommon" },
  { value: "turmeric latte with black pepper, for absorption",             band: "Uncommon" },
  { value: "loose-leaf tea weighed to the nearest 0.1 gram",               band: "Uncommon" },
  { value: "a mushroom coffee blend they brought from home",               band: "Uncommon" },
  { value: "iced coffee with collagen stirred in",                         band: "Uncommon" },
  { value: "a Starbucks Medicine Ball, every day, no exceptions",          band: "Rare" },
  { value: "four espresso shots over ice in a pint glass",                 band: "Rare" },
  { value: "a Thermos flask of green tea they have had since 2011",        band: "Rare" },
  { value: "a Diet Coke with two straws, poured over crushed ice",         band: "Rare" },
  { value: "a Monster Ultra Zero, warm, no ice, through a paper straw",    band: "Rare" },
  { value: "lukewarm lemon water with a specific pH they test daily",      band: "Rare" },
  { value: "a green juice with a handwritten ingredient list",             band: "Rare" },
  { value: "Soylent only, and will tell you about it",                     band: "Legendary" },
  { value: "raw milk from a farm they will not name",                      band: "Legendary" },
  { value: "a gallon of water a day, and you will hear about it",          band: "Legendary" },
  { value: "a kombucha SCOBY fermenting next to the keyboard",             band: "Mythic" },
  { value: "a jar of something cloudy they call 'the mother'",             band: "Mythic" },
];

const MEETING_ENERGY: TraitPool = [
  // Common (21)
  { value: "always on mute",                                                            band: "Common" },
  { value: "always 4 minutes late, always with a reason",                               band: "Common" },
  { value: "the one who unmutes to breathe, then mutes again",                          band: "Common" },
  { value: "dead silent with camera off",                                               band: "Common" },
  { value: "always eating something just off-screen",                                   band: "Common" },
  { value: "the one nodding slowly, saying nothing",                                    band: "Common" },
  { value: "chronically typing visibly during 'quick questions'",                       band: "Common" },
  { value: "the kind to leave exactly on the hour, mid-sentence",                       band: "Common" },
  { value: "always in a slightly darker room than everyone else",                       band: "Common" },
  { value: "the one whose dog appears halfway through",                                 band: "Common" },
  { value: "joining from the car, obviously",                                           band: "Common" },
  { value: "always sharing the wrong screen first",                                     band: "Common" },
  { value: "the one who says 'can you hear me?' three times",                           band: "Common" },
  { value: "the sort to reply 'sounds good' to everything",                             band: "Common" },
  { value: "always in the same hoodie, regardless of day",                              band: "Common" },
  { value: "the one fiddling with earbuds the whole call",                              band: "Common" },
  { value: "always the first to say 'I have a hard stop at the top of the hour'",      band: "Common" },
  { value: "the kind to keep a notebook open but never write in it",                    band: "Common" },
  { value: "the one who waves goodbye even on audio-only calls",                        band: "Common" },
  { value: "always two tabs deep in something unrelated",                               band: "Common" },
  { value: "the sort to ask 'sorry, can you repeat that?' every ten minutes",           band: "Common" },
  // Uncommon (12) — first entry is a rewrite of the legacy "interrupts with ..."
  { value: "the kind to interrupt with 'let me just jump in here'",                     band: "Uncommon" },
  { value: "the designated note-taker, unasked",                                        band: "Uncommon" },
  { value: "the chronic camera-positioner, never quite centred",                        band: "Uncommon" },
  { value: "the one who arrives exactly on time with a loaded agenda",                  band: "Uncommon" },
  { value: "the sort to pre-send a deck nobody opens",                                  band: "Uncommon" },
  { value: "prone to reading the slide aloud, word for word",                           band: "Uncommon" },
  { value: "the kind to ask 'can we park that?' without parking anything",              band: "Uncommon" },
  { value: "always the one with a hot take in the last 90 seconds",                     band: "Uncommon" },
  { value: "the one drinking from a mug that says something alarming",                  band: "Uncommon" },
  { value: "chronically at the wrong end of a bad ring light",                          band: "Uncommon" },
  { value: "the sort to volunteer other people for action items",                       band: "Uncommon" },
  { value: "the one who 'just wanted to pop in for a second' and stays the whole hour", band: "Uncommon" },
  // Rare (7) — first entry is a rewrite of the legacy "monologues for 47..."
  { value: "prone to 47-minute uninterrupted monologues",                               band: "Rare" },
  { value: "the one who says 'let's take a step back' every eight minutes",             band: "Rare" },
  { value: "chronically in a different meeting room than advertised",                   band: "Rare" },
  { value: "the sort to schedule a pre-meeting for the meeting",                        band: "Rare" },
  { value: "known for ending calls with 'well, this has been generative'",              band: "Rare" },
  { value: "the kind to open with 'I'll be brief' and never be brief",                  band: "Rare" },
  { value: "the one who brings printouts to a video call, somehow",                     band: "Rare" },
  // Legendary (3) — first entry is a rewrite of the legacy "books 7 a.m. ..."
  { value: "the sort who books 7 a.m. meetings 'to respect everyone's focus time'",     band: "Legendary" },
  { value: "famous for the 'quick sync' that lasts 90 minutes",                         band: "Legendary" },
  { value: "the one whose calendar invites include a mandatory reading list",           band: "Legendary" },
  // Mythic (2) — first entry is a rewrite of the legacy "speaks only in acronyms..."
  { value: "only ever heard speaking in acronyms nobody else recognises",               band: "Mythic" },
  { value: "known to have attended a meeting that later turned out not to exist",       band: "Mythic" },
];

const PASSIVE_AGGRESSIVE: TraitPool = [
  // Common (21) — widely-recognised corporate euphemisms
  { value: "Per my last email",                            band: "Common" },
  { value: "Just circling back",                           band: "Common" },
  { value: "Just following up",                            band: "Common" },
  { value: "Gentle reminder",                              band: "Common" },
  { value: "Friendly reminder",                            band: "Common" },
  { value: "Bumping this to the top of your inbox",        band: "Common" },
  { value: "Any update on this",                           band: "Common" },
  { value: "Just checking in",                             band: "Common" },
  { value: "As a reminder",                                band: "Common" },
  { value: "Not sure if you saw my last message",          band: "Common" },
  { value: "Hoping to close the loop on this",             band: "Common" },
  { value: "Flagging this again",                          band: "Common" },
  { value: "Wanted to make sure this didn't fall through the cracks", band: "Common" },
  { value: "Thanks in advance",                            band: "Common" },
  { value: "Noted",                                        band: "Common" },
  { value: "Thanks for your patience",                     band: "Common" },
  { value: "Just to be clear",                             band: "Common" },
  { value: "Looping back on this",                         band: "Common" },
  { value: "Sorry for the double email",                   band: "Common" },
  { value: "Pinging on this",                              band: "Common" },
  { value: "Tagging for visibility",                       band: "Common" },
  // Uncommon (12) — classic avoidance / deflection
  { value: "Happy to discuss offline",                     band: "Uncommon" },
  { value: "Let's take this to a smaller group",           band: "Uncommon" },
  { value: "I think there may be some confusion here",     band: "Uncommon" },
  { value: "Correct me if I'm wrong",                      band: "Uncommon" },
  { value: "With all due respect",                         band: "Uncommon" },
  { value: "Just my two cents",                            band: "Uncommon" },
  { value: "Going forward, let's make sure",               band: "Uncommon" },
  { value: "I'll let you two take it from here",           band: "Uncommon" },
  { value: "As I mentioned before",                        band: "Uncommon" },
  { value: "I'm sure you have a good reason for this",     band: "Uncommon" },
  { value: "Can you help me understand your thinking here", band: "Uncommon" },
  { value: "To your point",                                band: "Uncommon" },
  // Rare (7) — thinly-veiled hostility
  { value: "Resending with urgency (same email, 8 minutes later, red exclamation)", band: "Rare" },
  { value: "Reattaching the document you clearly didn't open", band: "Rare" },
  { value: "Cc'ing your manager so we're all aligned",     band: "Rare" },
  { value: "Moving this to the top of the thread for the third time", band: "Rare" },
  { value: "I'll take the silence as a yes",               band: "Rare" },
  { value: "Happy to jump on a call to explain it again",  band: "Rare" },
  { value: "Just so we're on the same page (we are not)",  band: "Rare" },
  // Legendary (3) — weapons-grade
  { value: "As discussed (it was not discussed)",          band: "Legendary" },
  { value: "Per our previous conversation (there was no previous conversation)", band: "Legendary" },
  { value: "Let me know your thoughts by EOD (it is currently 4:47 p.m.)", band: "Legendary" },
  // Mythic (2) — behaviour-as-phrase
  { value: "Adding a +1 with no further comment",          band: "Mythic" },
  { value: "Responding only with a calendar invite",       band: "Mythic" },
];

const PHYSICAL_HEIGHT: TraitPool = [
  { value: "average build",                                                band: "Common" },
  { value: "shorter than expected",                                        band: "Common" },
  { value: "a little stocky",                                              band: "Common" },
  { value: "slightly above average",                                       band: "Common" },
  { value: "shorter on camera than in person",                             band: "Common" },
  { value: "unremarkable",                                                 band: "Common" },
  { value: "medium, in every direction",                                   band: "Common" },
  { value: "wiry",                                                         band: "Common" },
  { value: "compact",                                                      band: "Common" },
  { value: "lanky",                                                        band: "Common" },
  { value: "a touch rounder than last year",                               band: "Common" },
  { value: "standard-issue",                                               band: "Common" },
  { value: "neither tall nor short",                                       band: "Common" },
  { value: "sturdy",                                                       band: "Common" },
  { value: "tall enough to comment on it",                                 band: "Uncommon" },
  { value: "gangly in a way colleagues have mentioned",                    band: "Uncommon" },
  { value: "tall enough that ceiling fans are a consideration",            band: "Uncommon" },
  { value: "broad-shouldered in a doorway-filling way",                    band: "Uncommon" },
  { value: "stocky and low to the ground",                                 band: "Uncommon" },
  { value: "noticeably small, in a way that becomes endearing",            band: "Uncommon" },
  { value: "the tallest person in most group photos",                      band: "Uncommon" },
  { value: "remarkably symmetrical for a person",                          band: "Uncommon" },
  { value: "somehow taller in meetings than in person",                    band: "Rare" },
  { value: "exactly the height of the average office chair",               band: "Rare" },
  { value: "a different height depending on who's describing them",        band: "Rare" },
  { value: "taller sitting down than seems geometrically possible",        band: "Rare" },
  { value: "looms",                                                        band: "Legendary" },
  { value: "cathedral-ceiling tall, with the acoustics to match",          band: "Legendary" },
  { value: "occupies more conceptual than physical space",                 band: "Mythic" },
  { value: "dimensionally ambiguous",                                      band: "Mythic" },
];

const PHYSICAL_ACCESSORY: TraitPool = [
  { value: "a single lanyard with one badge",                           band: "Common" },
  { value: "a corporate fleece",                                        band: "Common" },
  { value: "a standard-issue lanyard",                                  band: "Common" },
  { value: "an orange hi-vis backpack",                                 band: "Common" },
  { value: "a plain black tote bag from a conference",                  band: "Common" },
  { value: "a plastic wristwatch with the rubber strap going chalky",   band: "Common" },
  { value: "a clip-on pen in the breast pocket",                        band: "Common" },
  { value: "a branded water bottle with a dented lid",                  band: "Common" },
  { value: "a basic baseball cap, unbranded",                           band: "Common" },
  { value: "a set of keys on a retractable reel",                       band: "Common" },
  { value: "a navy scarf worn indoors",                                 band: "Common" },
  { value: "a wireless mouse in one hand, always",                      band: "Common" },
  { value: "a plain leather belt one hole too loose",                   band: "Common" },
  { value: "a cheap umbrella that won't quite fold away",               band: "Common" },
  { value: "reading glasses on a chain",                                band: "Uncommon" },
  { value: "a calculator watch they still use",                         band: "Uncommon" },
  { value: "an enamel pin from a 2014 team away-day",                   band: "Uncommon" },
  { value: "a bluetooth headset in only one ear",                       band: "Uncommon" },
  { value: "a fishing-tackle box repurposed for stationery",            band: "Uncommon" },
  { value: "a flip phone in a belt holster",                            band: "Uncommon" },
  { value: "a pocket notebook with everything underlined twice",        band: "Uncommon" },
  { value: "a brooch shaped like a swan, tarnished",                    band: "Uncommon" },
  { value: "a lanyard with 14 badges of varying importance",            band: "Rare" },
  { value: "a briefcase with three combination locks set to 000",       band: "Rare" },
  { value: "cufflinks shaped like tiny filing cabinets",                band: "Rare" },
  { value: "a pocket watch connected to nothing",                       band: "Rare" },
  { value: "a single shipwreck earring they will tell you about",       band: "Legendary" },
  { value: "a signet ring that clicks faintly when they sign forms",    band: "Legendary" },
  { value: "an ID badge from a company that no longer exists",          band: "Mythic" },
  { value: "a wristwatch displaying a timezone no cartographer agrees on", band: "Mythic" },
];

const PHYSICAL_EXPRESSION: TraitPool = [
  { value: "polite disappointment",                                            band: "Common" },
  { value: "neutral, unreadable",                                              band: "Common" },
  { value: "mild exhaustion",                                                  band: "Common" },
  { value: "quiet resolve",                                                    band: "Common" },
  { value: "patient disagreement",                                             band: "Common" },
  { value: "professional blankness",                                           band: "Common" },
  { value: "cautious optimism, slightly dented",                               band: "Common" },
  { value: "mid-afternoon glaze",                                              band: "Common" },
  { value: "controlled impatience",                                            band: "Common" },
  { value: "faint, practised encouragement",                                   band: "Common" },
  { value: "restrained weariness",                                             band: "Common" },
  { value: "soft bureaucratic concern",                                        band: "Common" },
  { value: "the careful neutrality of someone minuting a meeting",             band: "Common" },
  { value: "the composed flatness of a hold message",                          band: "Common" },
  { value: "the face of someone about to send a long email",                   band: "Uncommon" },
  { value: "the smile of someone who has mentally checked out",                band: "Uncommon" },
  { value: "the measured nod of someone disagreeing silently",                 band: "Uncommon" },
  { value: "the slow blink of someone rereading the same sentence",            band: "Uncommon" },
  { value: "the pinched look of someone about to cite a policy",               band: "Uncommon" },
  { value: "the polite grimace of a reply-all survivor",                       band: "Uncommon" },
  { value: "the faint smirk of someone sitting on a devastating CC",           band: "Uncommon" },
  { value: "the tight smile of someone who has been on mute for six minutes",  band: "Uncommon" },
  { value: "eyes that have seen SAP",                                          band: "Rare" },
  { value: "the vacant stare of Q4 reporting",                                 band: "Rare" },
  { value: "the thousand-yard stare of a failed migration",                    band: "Rare" },
  { value: "the haunted focus of someone reconciling a spreadsheet by hand",   band: "Rare" },
  { value: "permanently mid-sentence",                                         band: "Legendary" },
  { value: "frozen in a single corporate headshot since 2011",                 band: "Legendary" },
  { value: "wears nineteen subtly different smiles",                           band: "Mythic" },
  { value: "an expression that resolves differently depending on seniority",   band: "Mythic" },
];

const PHYSICAL_MATERIAL: TraitPool = [
  { value: "a cardigan, at least one",                              band: "Common" },
  { value: "polo shirt, jeans, sensible shoes",                     band: "Common" },
  { value: "permed hair that hasn't changed since 1994",            band: "Uncommon" },
  { value: "the exact outfit from their LinkedIn profile, 1999",    band: "Rare" },
  { value: "a tie pinned with what may be a live firefly",          band: "Legendary" },
  { value: "dressed entirely in clothes received as conference swag", band: "Mythic" },
];

const THEME_PRIMARY: TraitPool = [
  { value: "#9C6B3A", band: "Common" },     // office-tan
  { value: "#2D4A4F", band: "Common" },     // accountant teal
  { value: "#5C3D2E", band: "Uncommon" },   // boardroom mahogany
  { value: "#A23E48", band: "Rare" },       // expense-report red
  { value: "#1F4E79", band: "Legendary" },  // PowerPoint navy
  { value: "#FFCD3C", band: "Mythic" },     // overhead-projector yellow
];

const THEME_ACCENT: TraitPool = [
  { value: "#D9D9D9", band: "Common" },
  { value: "#7F7F7F", band: "Common" },
  { value: "#C0BFA8", band: "Uncommon" },
  { value: "#6E8B3D", band: "Rare" },
  { value: "#503D2E", band: "Legendary" },
  { value: "#FF6F61", band: "Mythic" },
];

/**
 * All trait pools, keyed by category name. The category names match the
 * keys used downstream by the roller and the per_trait breakdown.
 */
export const POOLS = {
  name: NAMES,
  job_title: JOB_TITLES,
  desk_setup: DESK_SETUPS,
  habit: HABITS,
  coffee_ritual: COFFEE_RITUALS,
  meeting_energy: MEETING_ENERGY,
  passive_aggressive: PASSIVE_AGGRESSIVE,
  physical_height: PHYSICAL_HEIGHT,
  physical_accessory: PHYSICAL_ACCESSORY,
  physical_expression: PHYSICAL_EXPRESSION,
  physical_material: PHYSICAL_MATERIAL,
  theme_primary: THEME_PRIMARY,
  theme_accent: THEME_ACCENT,
} as const;

export type CategoryKey = keyof typeof POOLS;
